server:
  port: 9200
  servlet:
    context-path: /act_admin_api

#配置数据源
spring:
  datasource:
    #配置jpa数据源（主-写）
    primary:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.111.155.104:3306/macalline_test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
      username: macalline_db
      password: macalline_db@5621df08A9df9E0
      # 初始化配置
      initial-size: 5
      # 最小连接数
      min-idle: 5
      # 最大连接数
      max-active: 20
      # 获取连接超时时间
      max-wait: 60000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 60000
      # 最大空闲时间
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      validation-query: select 1
      # 配置监控统计拦截的filters
      filters: stat
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false
      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
    #配置jpa数据源（从-读）
    read:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.111.155.104:3306/macalline_test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
      username: macalline_db
      password: macalline_db@5621df08A9df9E0
      # 初始化配置
      initial-size: 5
      # 最小连接数
      min-idle: 5
      # 最大连接数
      max-active: 20
      # 获取连接超时时间
      max-wait: 60000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 60000
      # 最大空闲时间
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

      validation-query: select 1
      # 配置监控统计拦截的filters
      filters: stat
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false
      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
    #配置mybatis数据源（主-从）
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      datasource:
        master:
          username: macalline_db
          password: macalline_db@5621df08A9df9E0
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://47.111.155.104:3306/macalline_test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
        slave:
          username: macalline_db
          password: macalline_db@5621df08A9df9E0
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://47.111.155.104:3306/macalline_test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false

  #配置 Jpa
  jpa:
    hibernate:
      # 生产环境设置成 none，避免程序运行时自动更新数据库结构
      ddl-auto: none
  rabbitmq:
    addresses: 47.111.155.104:5672
    username: macalline_mq
    password: macalline_mq@5621df08A9df9E0
    virtual-host: uat
    publisher-confirms: true
  redis:
    jedis:
      pool:
        max-wait: 1000
        max-Idle: 16
        min-Idle: 0
    cluster:
      nodes: 47.111.155.104:7001,47.111.155.104:7002,47.111.155.104:7003,47.111.155.104:7004,47.111.155.104:7005,47.111.155.104:7006
    timeout: 2000
    password: ab42QAXCE@23

#jwt
jwt:
  header: Authorization
  secret: mySecret
  # token 过期时间 2个小时
  expiration: 21000000
  auth:
    # 授权路径
    path: /login
    # 获取用户信息
    account: /info

#是否允许生成代码，生产环境设置为false
generator:
  enabled: true

#是否开启 swagger-ui
swagger:
  enabled: true